export const product = {
  handle: "bubble-sofa-mini",
  hasColorVariants: true,
  bundle: { x1Price: 29.9, x1Compare: 49.99, x2Price: 39.9, x2Compare: 99.98, x2Badge: "-10€ supplémentaires" },
  title: "3D Bubble Sofa Mini",
  vendor: "Cozy Corner",
  price: 29.9,
  compareAtPrice: 49.99,
  currency: "EUR",
  rating: 4.4,
  reviewCount: 40000,
  badge: "DÉSTOCKAGE",
  features: [
    "Des formes qui font tourner les têtes · Silhouette ronde et enveloppante, lignes organiques. On ne s'en lasse pas.",
    "Pivotant à 360° · Orientez-le vers la télé, la fenêtre ou vos invités. Il suit votre humeur.",
    "Tissu Techno 3D premium · Doux, texturé, résistant. Un revêtement qui change tout au toucher et au regard.",
    "Une couleur pour chaque intérieur · Large palette de coloris pour s'intégrer parfaitement à votre décor.",
  ],
  variants: [
    { name: "Blanc", swatch: "#f5f5f5", image: "/01.png" },
    { name: "Bleu", swatch: "#4a6fa5", image: "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/generated-image_11.png?v=1776879786" },
    { name: "Rose", swatch: "#eab6bf", image: "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/Gemini_Generated_Image_zbbxd9zbbxd9zbbx.png?v=1776879787" },
    { name: "Gris", swatch: "#8a8a8a", image: "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/Gemini_Generated_Image_ciq88ociq88ociq8.png?v=1776879786" },
    { name: "Rouge", swatch: "#b3261e", image: "/05.png" },
    { name: "Orange", swatch: "#e17a35", image: "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/bubble_fauteuil_120_pers1_F169_2.webp?v=1776879785" },
    { name: "Jaune", swatch: "#e5c036", image: "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/bubble_fauteuil_120_pers1_F169_3.webp?v=1776879785" },
    { name: "Vert Foncé", swatch: "#2e5e3e", image: "/08.png" },
  ],
  gallery: [
    "/01.png",
    "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/generated-image_11.png?v=1776879786",
    "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/Gemini_Generated_Image_zbbxd9zbbxd9zbbx.png?v=1776879787",
    "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/Gemini_Generated_Image_ciq88ociq88ociq8.png?v=1776879786",
    "/05.png",
    "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/bubble_fauteuil_120_pers1_F169_2.webp?v=1776879785",
    "https://cdn.shopify.com/s/files/1/0996/5512/3321/files/bubble_fauteuil_120_pers1_F169_3.webp?v=1776879785",
    "/08.png",
  ],
  details: [
    {
      q: "Caractéristiques techniques",
      a: [
        ["Dimensions", "L. 92 x H. 68 x P. 91 cm"],
        ["Revêtement", "Tissu Techno 3D"],
        ["Base", "Pivotante 360°"],
        ["Style", "Contemporain, design"],
        ["Coloris disponibles", "Large palette, dont Vert Topaze"],
        ["Éco-conception", "Oui"],
        ["Garantie", "30 jours satisfait ou remboursé"],
      ],
    },
    {
      q: "Contenu du colis",
      a: [
        "Tout ce qu'il vous faut pour transformer votre salon.",
        "✓ 1x 3D Bubble Sofa Mini",
        "✓ Livraison soignée incluse",
        "✓ CADEAU OFFERT : Coussin décoratif coordonné",
      ],
    },
    {
      q: "Livraison et retours gratuits",
      a: [
        "Toutes les commandes sont expédiées avec soin, avec des délais de livraison moyens de 5 à 7 jours ouvrés.",
        "Un numéro de suivi officiel vous sera fourni dès la prise en charge du colis.",
        "Vous disposez de 30 jours après réception pour nous retourner un article. Contactez simplement notre service client pour obtenir une étiquette de retour prépayée.",
      ],
    },
    {
      q: "Paiement sécurisé",
      a: [
        "Toutes les transactions effectuées sur notre site sont protégées par un chiffrement SSL 256 bits, identique à celui utilisé par les plus grandes institutions bancaires.",
        "Nous respectons les normes internationales les plus rigoureuses, telles que la certification ISO/IEC 27001 pour la sécurité de l'information et la norme PCI-DSS imposée aux prestataires de services de paiement.",
        "Pour renforcer davantage cette sécurité, nous collaborons exclusivement avec des partenaires de confiance tels que Stripe, PayPal et Visa/Mastercard SecureCode.",
        "Enfin, vos coordonnées bancaires ne sont jamais stockées sur nos serveurs, garantissant ainsi une confidentialité totale.",
      ],
    },
    {
      q: "Garantie satisfait ou remboursé",
      a: [
        "Chaque commande est automatiquement couverte par une assurance contre la perte, le vol ou les dommages pendant le transport.",
        "Nous offrons une garantie satisfait ou remboursé pendant 30 jours : retournez votre produit sans conditions et recevez un remboursement complet.",
        "Les remboursements sont traités dans un délai de 5 à 7 jours ouvrés après réception du retour.",
      ],
    },
  ],
  faq: [
    { q: "Le fauteuil est-il vraiment pivotant ?", a: "Oui, la base pivote à 360° pour s'orienter librement dans toutes les directions." },
    { q: "Puis-je choisir mon coloris ?", a: "Oui, plusieurs coloris sont disponibles. Sélectionnez le vôtre directement sur la fiche produit." },
    { q: "Quelle est la durée de livraison ?", a: "Comptez 5 à 7 jours ouvrés après validation de votre commande. Un numéro de suivi vous sera attribué." },
    { q: "Le fauteuil nécessite-t-il un montage ?", a: "Non, le fauteuil arrive prêt à utiliser. Posez-le, orientez-le et profitez immédiatement." },
    { q: "Quelles sont les dimensions exactes ?", a: "L. 92 x H. 68 x P. 91 cm. Un format compact idéal pour les salons, coins lecture ou espaces bureau." },
    { q: "Et si ça ne me convient pas ?", a: "30 jours pour retourner le produit, sans justification. Remboursement intégral." },
  ],
  reviews: [
    { name: "Camille R.", rating: 5, date: "Il y a 1 minute",        text: "Je l'ai vu et je l'ai commandé le même jour. Il est encore plus beau en vrai. Mon salon a une âme maintenant.",  image: "/reviews/hhh3_15.jpg", avatar: "/avatars/camille.jpg" },
    { name: "Marc D.",    rating: 5, date: "Il y a 2 minutes",       text: "La qualité du tissu est incroyable au toucher. Et la base pivotante est un vrai plus au quotidien.",             image: "/reviews/hhh2_18.jpg", avatar: "/avatars/marc.jpg" },
    { name: "Inès B.",    rating: 5, date: "Il y a 2 minutes",       text: "J'hésitais entre plusieurs coloris. J'ai pris le vert et c'est la meilleure décision déco que j'aie prise.",     image: "/reviews/hhh1_33.jpg", avatar: "/avatars/ines.jpg" },
    { name: "Thomas L.",  rating: 5, date: "Il y a quelques minutes", text: "Tout le monde me demande d'où il vient dès qu'ils entrent chez moi. C'est exactement ce que je cherchais.",     image: "/reviews/hhh4_9.jpg",  avatar: "/avatars/thomas.jpg" },
  ],
};

export const pressLogos = [
  { name: "Maisons du Monde", src: "https://astrasale.com/cdn/shop/files/Logo_Maisons_du_Monde_FR_8015e19c-494a-4ebf-af8a-795993af015a.png?v=1774671407&width=540" },
  { name: "Elle Décoration", src: "https://astrasale.com/cdn/shop/files/Elle_Decoration_regular_logo_svg_f2b83dbe-320a-407b-82dd-65083b41426b.png?v=1774671407&width=540" },
  { name: "Le Figaro", src: "https://astrasale.com/cdn/shop/files/Le_Figaro_Magazine_2014__logo.svg?v=1774267940&width=540" },
  { name: "Le Monde", src: "https://astrasale.com/cdn/shop/files/Le_monde_logo_svg_59c4eda5-85c1-4bff-ac2c-6baa73590fe1.png?v=1774671406&width=540" },
  { name: "Marie Claire", src: "https://astrasale.com/cdn/shop/files/Marie_Claire_Magazine_logo.svg_2_cd640df2-2fc1-4723-a18e-206c2a926b2b.png?v=1774671406&width=540" },
  { name: "Vogue", src: "https://astrasale.com/cdn/shop/files/VOGUE_LOGO_1.svg?v=1774268196&width=540" },
];
